
platform :ios, '8.0'
platform :ios, '7.0'
pod 'SDWebImage', '~>3.8'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'JSONModel'
pod 'BaiduMapKit'
target 'XQQYingyanDemo' do
pod 'AFNetworking', '~> 3.0'
end
